# Generated by Django 3.2.3 on 2021-05-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_vision_score'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
