# Generated by Django 3.2.3 on 2021-05-25 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_vision_score'),
        ('community', '0002_community_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='movie',
        ),
        migrations.AddField(
            model_name='community',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
