# Generated by Django 3.2.3 on 2021-05-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210525_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
    ]
