# Generated by Django 3.2.3 on 2021-05-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('movie', models.ManyToManyField(to='movies.Movie')),
            ],
        ),
    ]
